### ISSUE TITLE
Question about fixmatch baseline

### ISSUE THREAD

**Issue by komejisatori** [YUE-FAN/SSB#1]
Thanks for your excellent work! Could you please tell me how to reimplement the fixmatch results in your paper (e.g. in Fig.3)?

**Comment by YUE-FAN** [comment]
Hi, thanks for your interest. Simply run the following command for CIFAR10 with 25 labels per class: 
`python main_fix.py --dataset cifar10 --num-labeled 25 --out ./saved_models/cifar10/fixmatch/wresnetleaky2_C6_N25_mlp3_head1024_seed1 --arch wideresnet --lambda_x 1 --lambda_u 1 --lambda_oem 0.1 --lambda_socr 0.5 --batch-size 64 --mu 2 --lr 0.03 --expand-labels --seed 1 --opt_level O2 --no-progress --both_head_increment mlp3 --threshold 0.95 --hidden_dim_increment 1024`
